- name: Update packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "update_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "update_{{ ansible_distribution }}.yml"
